compile:	
	@echo ">>>> Was macht eine Elster im Rechenzentrum?"
	@sleep 3.5
	@echo ""
	@echo "                         ▒▒"
	@sleep 1                                     
	@echo "                         ▒▒"
	@sleep 1
	@echo "                         ▒▒"
	@sleep 1
	@echo "                         ▒▒"
	@echo ""
	@echo "▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  Sie Cloud Server!   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒"
	@echo "****************                      *****************"
	@echo ""
	@echo "*******************************************************"
	@sleep 1
run:
	@python3 client.py jsonLove

run_extra:
	@echo "this script has to be executed with sudo. that's why your password is needed:"
	@sudo python3 sniffer.py 

