compile:	
	@echo ">>>> Was macht eine Elster im Rechenzentrum?"
	@sleep 3.5
	@echo ""
	@echo "                         ▒▒"
	@sleep 1                                     
	@echo "                         ▒▒"
	@sleep 1
	@echo "                         ▒▒"
	@sleep 1
	@echo "                         ▒▒"
	@echo ""
	@echo "▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  Sie Cloud Server!   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒"
	@echo "****************                      *****************"
	@echo ""
	@echo "*******************************************************"
	@sleep 1
run:
	@python3 client.py jsonLOVER1000

run_extra:
	@cmatrix 
