apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
  namespace: sachs
spec:
  replicas: 1
  strategy:
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: registry.datexis.com/ksachs/test
          ports:
            - name: client-port
              containerPort: 8080
          resources:
            requests:
              cpu: "1"
              memory: 16Gi
            limits:
              cpu: "4"
              memory: 64Gi
      imagePullSecrets:
        - name:  private-registry-auth

